check linter

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,66 +1,32 @@
-name: runTests
+name: cpp-linter
 
 on:
-  pull_request: 
-    branches:
-      - master
-      - main
-    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake']
   push:
-    branches: 
-      - '*'
-    paths: ['**.c', '**.cpp', '**.h', '**.hpp', '**.cxx', '**.hxx', '**.cc', '**.hh', '**CMakeLists.txt', 'meson.build', '**.cmake']
+    paths:
+      - "*"
+  pull_request:
+    paths:
+      - "*"
+
+
 jobs:
-  TestOnUbuntu:
-    needs: FormatCode
+  cpp-linter:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Install cpp + cmake
-        run: |
-          sudo apt-get install -y cmake
-          sudo apt-get install -y ninja-build
-          sudo apt-get install -y g++
-      - name: Build
-        run: |
-          mkdir build
-          cd build
-          cmake -G Ninja ../backend
-          ninja
-      - name: Setup Python
-        run: | 
-          sudo apt-get install -y python3
-          sudo apt-get install -y python3-pip
-          mv backend ../tests
-          cd ../tests
-      - name: Start Tests
-        run: |
-          cd tests
-          ls
-          python3 tester.py
-  FormatCode:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Install clang-format
-        run: |
-          sudo apt-get install -y clang-format
-      - uses: cpp-linter/cpp-linter-action@v2
+      - uses: actions/checkout@v4
+      - uses: cpp-linter/cpp-linter-action@main
         id: linter
+        continue-on-error: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          style: 'file'
-          tidy-checks: '-*'
+          style: file
+          files-changed-only: false
+          thread-comments: false
 
-      - name: PushOnGit
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed != 0
         run: |
-          git config --global user.email "your-email@example.com"
-          git config --global user.name "your-username"
-          git add .
-          git commit -m "Automated code formatting" || echo "No changes to commit"
-          git push
+          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
+        # for actual deployment
+        # run: exit 1
